services:
  - type: web
    name: gurukul-school
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: gurukul-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: gurukul-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: gurukul-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gurukul-db
          property: password

databases:
  - name: gurukul-db
    plan: free
    region: singapore
    ipAllowList: []
